hash_path = ["0x1053e87bed5f2a4f5144b386c5403701212f4b3c21cb14683b6ebdfed16c854d", "0x1e8e7c1e1f6f65d0d3553e0f715c335f0ccdcc21cda1df7355e6c6e851bccf54"]
index = "0"
priv_key = "0"
proposalId = "0"
root = "0x20c77d6d51119d86868b3a37a64cd4510abd7bdb7f62a9e78e51fe8ca615a194"
secret = "9"
vote = "1"