proposalId = "0x0000000000000000000000000000000000000000000000000000000000000000"
return = "0x0bf0dd2fad1a8da018371f0a8dac56016d270d2e178a847a3ac724d033d1d858"
root = "0x20c77d6d51119d86868b3a37a64cd4510abd7bdb7f62a9e78e51fe8ca615a194"
vote = "0x0000000000000000000000000000000000000000000000000000000000000001"
